#!/bin/bash

###### PART 2 (after relog to new account)

pulseaudio --start

wget https://aur.archlinux.org/cgit/aur.git/snapshot/packer.tar.gz
tar -xvzf packer.tar.gz
cd packer
makepkg --noconfirm -si
cd ..
rm -rf packer/
rm packer.tar.gz

packer --noconfirm -S cli-visualizer neomutt i3-gaps-next-git ttf-font-awesome vim-pathogen vim-live-latex-preview projectm-pulseaudio taffy neofetch i3lock tamzen-font-git speedometer nodejs-markdown-pdf arpoison iputils iproute2 inetutils moka-icon-theme-git ttf-freefont ttf-arphic-uming ttf-baekmuk imgur-screenshot-git xclip 

#wget http://lukesmith.xyz/longterm/lukerice.tar.gz
#tar -xvzf lukerice.tar.gz
#rsync -va --delete-after lukerice/ ~



cd ~/.config
mkdir bumblebee-status
cd bumblebee-status/
git clone git://github.com/tobi-wan-kenobi/bumblebee-status


cd ~/Documents/
git clone https://github.com/camiotw/dotfileswip.git
cd dotfileswip/
rsync -va i3/ ~/.i3/
rsync -va archsetup/.bashrc ~/.bashrc_CAMIO
rsync -va archsetup/setup ~/Documents/"Arch Setup.txt"
rsync -va archsetup/lukerice ~/Documents
rsync -va archsetup/OLD ~/Documents
rsync -va etc/ ~/Documents
#rsync -va etc/WHATNOW ~/WHATNOW

# Add whatnow file with info like adding user to [users] group
# and to add sudoers pw?

# WHOAMI=$(whoami)
# useradd -m -g users -s /bin/bash $WHOAMI
#
# echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# admin    ALL=(ALL) ALL
# admin    ALL = NOPASSWD: ALL

echo "Congratulations. Installation complete."
echo ""
echo "Now enter \"startx\" to enter the desktop if you are in a tty."
echo ""
echo "If you are using a login manager, you should be able to log off and log back in in i3 as this user for the same effect."
